

# spring:
#   application:
#      name: Config-default
eurekar:
  client:
     fetch-registry: true
     retister-with-eureka: true
     service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
     prefer-ip-address: true
